# App-specific tweaks
source = ~/.local/share/yavaos/config/hypr/apps/bitwarden.conf
source = ~/.local/share/yavaos/config/hypr/apps/browser.conf
source = ~/.local/share/yavaos/config/hypr/apps/hyprshot.conf
source = ~/.local/share/yavaos/config/hypr/apps/jetbrains.conf
source = ~/.local/share/yavaos/config/hypr/apps/localsend.conf
source = ~/.local/share/yavaos/config/hypr/apps/pip.conf
source = ~/.local/share/yavaos/config/hypr/apps/qemu.conf
source = ~/.local/share/yavaos/config/hypr/apps/retroarch.conf
source = ~/.local/share/yavaos/config/hypr/apps/steam.conf
source = ~/.local/share/yavaos/config/hypr/apps/geforce.conf
source = ~/.local/share/yavaos/config/hypr/apps/system.conf
source = ~/.local/share/yavaos/config/hypr/apps/telegram.conf
source = ~/.local/share/yavaos/config/hypr/apps/terminals.conf
source = ~/.local/share/yavaos/config/hypr/apps/walker.conf
source = ~/.local/share/yavaos/config/hypr/apps/rofi.conf
source = ~/.local/share/yavaos/config/hypr/apps/webcam-overlay.conf
source = ~/.local/share/yavaos/config/hypr/apps/waybar.conf
source = ~/.local/share/yavaos/config/hypr/apps/kitty.conf
source = ~/.local/share/yavaos/config/hypr/apps/telegram.conf
source = ~/.local/share/yavaos/config/hypr/apps/vscode.conf
