add_newline = true
command_timeout = 200

format = """
╭─$username$hostname$directory$git_branch$git_status$kubernetes
╰─($style)$character"""

[username]
show_always = true
style_user = "white"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "white"
format = "[@$hostname]($style) "

[directory]
truncation_length = 2
truncation_symbol = "…/"
style = "bold cyan"
format = "[$path]($style) "
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[kubernetes]
disabled = false
style = "bold blue"
format = "([$symbol|($context:$namespace)]($style)) "
symbol = "⎈"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[❯](bold cyan)"

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
